/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.treasurehuntgame;

import java.awt.Color;
import java.util.Random;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author mehmetenes
 */
public class Game extends javax.swing.JFrame {

    /**
     * Creates new form Game
     */
    // Userı tutmak için Game sınıfı user alıyor.
    static User user;
    private JLabel[] mapLabels;
    private LinkedListMap map;
    int currentLevel = 1; // Güncel leveli tutar.

    public Game(User user) {
        this.user = user;
        initComponents();

        mapLabels = new JLabel[]{
            jLabel1, jLabel2, jLabel3, jLabel4, jLabel5, jLabel6,
            jLabel7, jLabel8, jLabel9, jLabel10, jLabel11, jLabel12,
            jLabel13, jLabel14, jLabel15, jLabel16, jLabel17, jLabel18,
            jLabel19, jLabel20, jLabel21, jLabel22, jLabel23, jLabel24,
            jLabel25, jLabel26, jLabel27, jLabel28, jLabel29, jLabel30
        };

        System.out.println(user.username); // Kullanıcı kontrolü
        startGame(user);
    }

    public void initializeMapDisplay(LinkedListMap map, JLabel[] mapLabels) {
        MapNode current = map.head;
        int i = 0;
        while (current != null && i < mapLabels.length) {
            String text = switch (current.type) {
                case "treasure" ->
                    "💰 Treasure";
                case "trap" ->
                    "💀 Trap";
                case "forward" ->
                    "➡️ Forward";
                case "backward" ->
                    "⬅️ Backward";
                default ->
                    "🕳️ Empty";
            };
            mapLabels[i].setText(text);
            current = current.next;
            i++;
        }
    }

    private void startGame(User user) {
        map = new LinkedListMap(30, currentLevel); // Güncel levele göre harita üretir.
        initializeMapDisplay(map, mapLabels);
        map.displayMap();
        Random rand = new Random();
        user.resetPosition();
        user.resetScore();
    }

    private void updatePlayerPosition(int oldPos, int newPos) {
        System.out.println("old: " + oldPos + " new: " + newPos);
        if (oldPos >= 0 && oldPos < mapLabels.length) {
            mapLabels[oldPos].setForeground(null); // eski rengi sıfırla
        }
        if (newPos >= 0 && newPos < mapLabels.length) {
            mapLabels[newPos].setForeground(Color.GREEN); // oyuncunun yeri
        }
    }

    private void isOver() {
        ScoreManager.saveScore(user, currentLevel);
        if (currentLevel >= 3) {
            JOptionPane.showMessageDialog(null, "Game Over! You completed all levels.");
            this.dispose();  // Oyunu kapat
            return;
        }
        int result = JOptionPane.showConfirmDialog(null, "Level " + currentLevel + " is over. Do you want to continue to Level " + (currentLevel + 1) + "?", "Continue?",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE);

        if (result == JOptionPane.YES_OPTION) {
            currentLevel++;
            mapLabels[user.currentNode.index].setForeground(null);
            startGame(user);
        } else {
            JOptionPane.showMessageDialog(null, "Game Over! Thanks for playing.");
            this.dispose();  // Oyunu kapat
        }
    }

    private void level2Movement() {
        Random random = new Random();
        while (user.currentNode != null && (user.currentNode.type == "forward" || user.currentNode.type == "backward")) {
            int oldIndex = user.currentNode.index;
            if (user.currentNode.type.equals("forward")) {
                int forward = random.nextInt(6) + 5;
                int tentativeIndex = user.currentNode.index + forward;

                if (tentativeIndex > 29) {
                    System.out.println("Level is over");
                    isOver();
                    return; // level2Movement()’ten çık
                }

                user.currentNode.index = tentativeIndex;
                user.moveForward(forward);
                updatePlayerPosition(oldIndex, user.currentNode.index);
                System.out.println("İleri atladı: " + forward);

            } else if (user.currentNode.type == "backward") {
                int backward = random.nextInt(6) + 5;
                user.moveBackward(backward);
                updatePlayerPosition(oldIndex, Math.max(0, user.currentNode.index));
                System.out.println("Geri atladı: " + backward);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1100, 700));
        getContentPane().setLayout(null);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(330, 620, 60, 40);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(410, 580, 50, 30);
        getContentPane().add(jLabel3);
        jLabel3.setBounds(500, 560, 42, 17);
        getContentPane().add(jLabel4);
        jLabel4.setBounds(590, 570, 60, 30);
        getContentPane().add(jLabel5);
        jLabel5.setBounds(690, 590, 42, 17);
        getContentPane().add(jLabel6);
        jLabel6.setBounds(780, 570, 70, 40);
        getContentPane().add(jLabel7);
        jLabel7.setBounds(880, 540, 70, 40);
        getContentPane().add(jLabel8);
        jLabel8.setBounds(900, 470, 60, 30);
        getContentPane().add(jLabel9);
        jLabel9.setBounds(830, 420, 60, 30);
        getContentPane().add(jLabel10);
        jLabel10.setBounds(750, 400, 50, 40);
        getContentPane().add(jLabel11);
        jLabel11.setBounds(650, 420, 60, 30);
        getContentPane().add(jLabel12);
        jLabel12.setBounds(570, 410, 50, 40);
        getContentPane().add(jLabel13);
        jLabel13.setBounds(470, 390, 60, 40);
        getContentPane().add(jLabel14);
        jLabel14.setBounds(390, 360, 50, 40);
        getContentPane().add(jLabel15);
        jLabel15.setBounds(300, 340, 60, 40);
        getContentPane().add(jLabel16);
        jLabel16.setBounds(200, 320, 70, 40);
        getContentPane().add(jLabel17);
        jLabel17.setBounds(130, 280, 50, 40);
        getContentPane().add(jLabel18);
        jLabel18.setBounds(120, 200, 60, 40);
        getContentPane().add(jLabel19);
        jLabel19.setBounds(180, 140, 50, 40);
        getContentPane().add(jLabel20);
        jLabel20.setBounds(250, 100, 60, 40);
        getContentPane().add(jLabel21);
        jLabel21.setBounds(330, 100, 60, 40);
        getContentPane().add(jLabel22);
        jLabel22.setBounds(430, 120, 60, 40);
        getContentPane().add(jLabel23);
        jLabel23.setBounds(470, 190, 60, 40);
        getContentPane().add(jLabel24);
        jLabel24.setBounds(460, 260, 60, 40);
        getContentPane().add(jLabel25);
        jLabel25.setBounds(540, 300, 60, 40);
        getContentPane().add(jLabel26);
        jLabel26.setBounds(660, 300, 70, 40);
        getContentPane().add(jLabel27);
        jLabel27.setBounds(750, 260, 70, 40);
        getContentPane().add(jLabel28);
        jLabel28.setBounds(830, 210, 70, 40);
        getContentPane().add(jLabel29);
        jLabel29.setBounds(910, 150, 60, 40);
        getContentPane().add(jLabel30);
        jLabel30.setBounds(960, 70, 70, 60);

        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dice.png"))); // NOI18N
        getContentPane().add(jLabel32);
        jLabel32.setBounds(0, 0, 150, 120);

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background.png"))); // NOI18N
        getContentPane().add(jLabel31);
        jLabel31.setBounds(0, 0, 1100, 710);

        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(50, 0, 90, 120);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Random rand = new Random();
        int dice = rand.nextInt(6) + 1;
        System.out.println("Zar: " + dice);
        int oldIndex = -1;

        if (user.currentNode != null) {
            oldIndex = user.currentNode.index;
        }

        jLabel31.setText("zar: " + dice);
        if (user.currentNode == null) {
            user.currentNode = map.getNodeAtFirst(dice);
            updatePlayerPosition(oldIndex, user.currentNode.index);

        } else if (user.currentNode.index + dice <= 29) {
            user.moveForward(dice);
            updatePlayerPosition(oldIndex, user.currentNode.index);
        } else {
            isOver();
        }
        if (currentLevel == 2) {
            level2Movement();
        }
        if (user.currentNode != null) {
            System.out.println(user.currentNode.type);
            user.updateScore(user.currentNode.type);
        }
        System.out.println("Score: " + user.score);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Game.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Game.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Game.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Game.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Game(user).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
